# -- Template input file

# Path where the monitoring and output data will be stored
output_path: './status'

# Basic properties of the dataset used
dataset: {
    # Identifiers of the dataset
    id: {
      prefix: '',
      suffix: '',
    },
    # Basic parameters of the dataset
    parameters: {
        Nb: 2000, 
        Nt: 64, 
        Nw: 1000, 
        Ns: 32, 
        w_range: [0.0, 8.0],
    },
    # Generation information of the dataset
    generation: {
      # Overwrite the dataset if it already existst
      overwrite: False,
      # File to be used as basis functions; '' means new generation of basis functions
      basis: '',
      # Use the GPU in the computation of the basis functions
      use_GPU: True,
    },
    # Peaks used in the dataset
    peaks: {
      # Peak class and identifier; use classname(:\w+)?. Classes need to be registered
      peaks_used:  ['GaussianPeak:test'],
      max_np: 1,
      fixed_np: True,
      limits: {
          Mtest: [0.3,  3.0],
          Atest: [0.1,  1.0],
          Wtest: [0.05, 0.1],
      },
    },
    # Kernel used in the dataset; kernel needs to be registered.
    kernel: 'NRQCDKernel',
}

# -- Basic properties of the network used
network: {
    # Prefix used to further specify a network
    prefix: 'test',
    # Proportion of the whole dataset used in the validation step
    val_prop: 0.5,
    # Number of epochs used in the training step
    epochs: 2,
    # Batch size used in the training
    batch_size: 100,
}
