# -- Template input file

# Path where the monitoring and output data will be stored
dataset: {
  id: {
    prefix: '',
    suffix: '',
  },
  parameters: {
    Nb: 2000,
    Nt: 64,
    Ns: 32,
    Nw: 1000,
    wr: [0.0, 8.0],
    mp: 2,
    fp: True,
  },
  generation: {
    # Overwrite the dataset if it already existst
    overwrite: False,
    # File to be used as basis functions; '' means new generation of basis functions
    basis: '',
    # Use the GPU in the computation of the basis functions
    use_GPU: True,
  },
  # Peaks used in the dataset
  peaks: {
    # Peak class and identifier; use classname(:\w+)?. Classes need to be registered
    peaks_used:  ['GaussianPeak:test'],
    max_np: 1,
    fixed_np: True,
    limits: {
        Mtest: [0.3,  3.0],
        Atest: [0.1,  1.0],
        Wtest: [0.05, 0.1],
    },
  },
  # Kernel used in the dataset; kernel needs to be registered.
  kernel: 'NRQCDKernel',
}

# -- Define the network used
network: {
  # Network to be used in the calculation. Needs to be registered
  type: 'UNet',
  # String identifier of the network
  name: 'test',
}

# -- Train and validation parameters
train: {
  # Number of examples in the validation dataset
  val_Nb: 1000,
  # Number of epochs used in the training step
  epochs: 5,
  # Batch size used in the training
  batch_size: 100,
  # Learning rate decay parameter
  lr_decay: 0.95,
}
