# Checks that we can build and validate the Unittest
name: Test spectrec

on: [push]

jobs:

  ci:
    # -- Set the strategy and the matrix 
    strategy:
      fail-fast: false
      matrix:
        poetry-version: [1.1.10]

    # -- Set the platform used to test the data
    runs-on: ubuntu-latest

    # -- Steps of the continuous integration
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

          # - name: Cache Poetry virtualenv
          #   uses: actions/cache@v1
          #   id: cache
          #   with:
          #     path: ~/.virtualenvs
          #     key: poetry-$
          #     restore-keys: |
          #       poetry-$
