# Checks that we can build and validate the Unittest
name: spectrec 

on: [push]

jobs:

  ci:
    # -- Set the strategy and the matrix 
    strategy:
      fail-fast: false
      matrix:
        poetry-version: [1.1.10]

    # -- Set the platform used to test the data
    runs-on: ubuntu-latest

    # -- Steps of the continuous integration
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run pytest
        run: PYTHONPATH=spectrec/ poetry run python -m pytest -v --cov=spectrec/ tests/

      - name: Run pytest coverage
        run: PYTHONPATH=spectrec/ poetry run python -m coverage report -m;

      - name: Generate XML Report
        run: PYTHONPATH=spectrec/ poetry run python -m coverage xml
